// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAR4ntFfMcIyqrXh09YPl6zn3wtlpIgvM',
    appId: '1:751069500975:web:c2859073b95db30e3b58da',
    messagingSenderId: '751069500975',
    projectId: 'chaty-91c80',
    authDomain: 'chaty-91c80.firebaseapp.com',
    storageBucket: 'chaty-91c80.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALWh9YshbYMNzwYIsTBcr0DmWsmXdNm5U',
    appId: '1:751069500975:android:9dcb7870803f19793b58da',
    messagingSenderId: '751069500975',
    projectId: 'chaty-91c80',
    storageBucket: 'chaty-91c80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkaqiPFjV-rcPbWKfD1YTQTjHYweXiB_0',
    appId: '1:751069500975:ios:0478542e386b59303b58da',
    messagingSenderId: '751069500975',
    projectId: 'chaty-91c80',
    storageBucket: 'chaty-91c80.firebasestorage.app',
    iosBundleId: 'com.example.chaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkaqiPFjV-rcPbWKfD1YTQTjHYweXiB_0',
    appId: '1:751069500975:ios:0478542e386b59303b58da',
    messagingSenderId: '751069500975',
    projectId: 'chaty-91c80',
    storageBucket: 'chaty-91c80.firebasestorage.app',
    iosBundleId: 'com.example.chaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAR4ntFfMcIyqrXh09YPl6zn3wtlpIgvM',
    appId: '1:751069500975:web:51c893db25a7c64e3b58da',
    messagingSenderId: '751069500975',
    projectId: 'chaty-91c80',
    authDomain: 'chaty-91c80.firebaseapp.com',
    storageBucket: 'chaty-91c80.firebasestorage.app',
  );
}
